services:
  proposta-service:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: proposta-service
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - Database__Host=postgres-infra
      - Database__Name=propostadb
      - Database__Port=5432
      - RabbitMQ__Host=rabbitmq-infra
      - RabbitMQ__Port=5672
    secrets:
      - postgres_user
      - postgres_password
      - rabbitmq_user
      - rabbitmq_password
    restart: unless-stopped
    networks:
      - propostaservice_microservices-network

secrets:
  postgres_user:
    file: ./secrets/postgres_user.txt
  postgres_password:
    file: ./secrets/postgres_password.txt
  rabbitmq_user:
    file: ./secrets/rabbitmq_user.txt
  rabbitmq_password:
    file: ./secrets/rabbitmq_password.txt

networks:
  propostaservice_microservices-network:
    external: true
