services:
  postgres:
    image: postgres:15
    container_name: postgres-infra
    environment:
      POSTGRES_DB: propostadb
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./secrets/postgres_user.txt:/run/secrets/postgres_user:ro
      - ./secrets/postgres_password.txt:/run/secrets/postgres_password:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$(cat /run/secrets/postgres_user)"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - microservices-network

  rabbitmq:
    build:
      context: .
      dockerfile: rabbitmq/Dockerfile
    container_name: rabbitmq-infra
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./secrets/rabbitmq_user.txt:/run/secrets/rabbitmq_user:ro
      - ./secrets/rabbitmq_password.txt:/run/secrets/rabbitmq_password:ro
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - microservices-network

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  microservices-network:
    driver: bridge
